CREATE OR REPLACE TABLE USER {
    ID BIGINT,
    NICKNAME VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    PRIMARY KEY (ID)
};

CREATE OR REPLACE TABLE BOOK {
    ID BIGINT,
    TITLE VARCHAR(200) NOT NULL,
    RESUME VARCHAR(10000) NOT NULL,
    AUTHOR_ID BIGINT NOT NULL,
    EDITORIAL VARCHAR(200) NOT NULL,
    PUBLICATION_DATE DATE NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES USER (ID)
};

CREATE OR REPLACE COMMENT {
    ID BIGINT,
    BOOK_ID BIGINT NOT NULL,
    AUTHOR_ID BIGINT NOT NULL,
    COMMENT VARCHAR(1000) NOT NULL,
    POINTS INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES USER (ID)
};

/*
 GRANTS
 SEQUENCES
*/

